package com.miget.hxb.domain;

import com.miget.hxb.model.BasicDomain;

import java.time.OffsetDateTime;

public class BizOrder extends BasicDomain {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbiz_order.order_id
     *
     * @mbg.generated Thu May 17 14:04:47 CST 2018
     */
    private Long orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbiz_order.user_id
     *
     * @mbg.generated Thu May 17 14:04:47 CST 2018
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbiz_order.address_id
     *
     * @mbg.generated Thu May 17 14:04:47 CST 2018
     */
    private Integer addressId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbiz_order.amount
     *
     * @mbg.generated Thu May 17 14:04:47 CST 2018
     */
    private Long amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbiz_order.is_payed
     *
     * @mbg.generated Thu May 17 14:04:47 CST 2018
     */
    private Integer isPayed;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbiz_order.pay_id
     *
     * @mbg.generated Thu May 17 14:04:47 CST 2018
     */
    private Integer payId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbiz_order.pay_type
     *
     * @mbg.generated Thu May 17 14:04:47 CST 2018
     */
    private Integer payType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbiz_order.create_time
     *
     * @mbg.generated Thu May 17 14:04:47 CST 2018
     */
    private OffsetDateTime createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbiz_order.update_time
     *
     * @mbg.generated Thu May 17 14:04:47 CST 2018
     */
    private OffsetDateTime updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbiz_order.operator
     *
     * @mbg.generated Thu May 17 14:04:47 CST 2018
     */
    private String operator;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbiz_order.order_id
     *
     * @return the value of tbiz_order.order_id
     *
     * @mbg.generated Thu May 17 14:04:47 CST 2018
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbiz_order.order_id
     *
     * @param orderId the value for tbiz_order.order_id
     *
     * @mbg.generated Thu May 17 14:04:47 CST 2018
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbiz_order.user_id
     *
     * @return the value of tbiz_order.user_id
     *
     * @mbg.generated Thu May 17 14:04:47 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbiz_order.user_id
     *
     * @param userId the value for tbiz_order.user_id
     *
     * @mbg.generated Thu May 17 14:04:47 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbiz_order.address_id
     *
     * @return the value of tbiz_order.address_id
     *
     * @mbg.generated Thu May 17 14:04:47 CST 2018
     */
    public Integer getAddressId() {
        return addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbiz_order.address_id
     *
     * @param addressId the value for tbiz_order.address_id
     *
     * @mbg.generated Thu May 17 14:04:47 CST 2018
     */
    public void setAddressId(Integer addressId) {
        this.addressId = addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbiz_order.amount
     *
     * @return the value of tbiz_order.amount
     *
     * @mbg.generated Thu May 17 14:04:47 CST 2018
     */
    public Long getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbiz_order.amount
     *
     * @param amount the value for tbiz_order.amount
     *
     * @mbg.generated Thu May 17 14:04:47 CST 2018
     */
    public void setAmount(Long amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbiz_order.is_payed
     *
     * @return the value of tbiz_order.is_payed
     *
     * @mbg.generated Thu May 17 14:04:47 CST 2018
     */
    public Integer getIsPayed() {
        return isPayed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbiz_order.is_payed
     *
     * @param isPayed the value for tbiz_order.is_payed
     *
     * @mbg.generated Thu May 17 14:04:47 CST 2018
     */
    public void setIsPayed(Integer isPayed) {
        this.isPayed = isPayed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbiz_order.pay_id
     *
     * @return the value of tbiz_order.pay_id
     *
     * @mbg.generated Thu May 17 14:04:47 CST 2018
     */
    public Integer getPayId() {
        return payId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbiz_order.pay_id
     *
     * @param payId the value for tbiz_order.pay_id
     *
     * @mbg.generated Thu May 17 14:04:47 CST 2018
     */
    public void setPayId(Integer payId) {
        this.payId = payId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbiz_order.pay_type
     *
     * @return the value of tbiz_order.pay_type
     *
     * @mbg.generated Thu May 17 14:04:47 CST 2018
     */
    public Integer getPayType() {
        return payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbiz_order.pay_type
     *
     * @param payType the value for tbiz_order.pay_type
     *
     * @mbg.generated Thu May 17 14:04:47 CST 2018
     */
    public void setPayType(Integer payType) {
        this.payType = payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbiz_order.create_time
     *
     * @return the value of tbiz_order.create_time
     *
     * @mbg.generated Thu May 17 14:04:47 CST 2018
     */
    public OffsetDateTime getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbiz_order.create_time
     *
     * @param createTime the value for tbiz_order.create_time
     *
     * @mbg.generated Thu May 17 14:04:47 CST 2018
     */
    public void setCreateTime(OffsetDateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbiz_order.update_time
     *
     * @return the value of tbiz_order.update_time
     *
     * @mbg.generated Thu May 17 14:04:47 CST 2018
     */
    public OffsetDateTime getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbiz_order.update_time
     *
     * @param updateTime the value for tbiz_order.update_time
     *
     * @mbg.generated Thu May 17 14:04:47 CST 2018
     */
    public void setUpdateTime(OffsetDateTime updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbiz_order.operator
     *
     * @return the value of tbiz_order.operator
     *
     * @mbg.generated Thu May 17 14:04:47 CST 2018
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbiz_order.operator
     *
     * @param operator the value for tbiz_order.operator
     *
     * @mbg.generated Thu May 17 14:04:47 CST 2018
     */
    public void setOperator(String operator) {
        this.operator = operator;
    }
}