package com.miget.hxb.domain;

import com.miget.hxb.model.BasicDomain;

import java.time.OffsetDateTime;

public class BizOrderItem extends BasicDomain {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbiz_order_item.order_item_id
     *
     * @mbg.generated Thu May 17 14:04:47 CST 2018
     */
    private Long orderItemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbiz_order_item.order_id
     *
     * @mbg.generated Thu May 17 14:04:47 CST 2018
     */
    private Long orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbiz_order_item.product_id
     *
     * @mbg.generated Thu May 17 14:04:47 CST 2018
     */
    private Integer productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbiz_order_item.business_id
     *
     * @mbg.generated Thu May 17 14:04:47 CST 2018
     */
    private Integer businessId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbiz_order_item.product_count
     *
     * @mbg.generated Thu May 17 14:04:47 CST 2018
     */
    private Integer productCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbiz_order_item.product_price
     *
     * @mbg.generated Thu May 17 14:04:47 CST 2018
     */
    private Integer productPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbiz_order_item.amount
     *
     * @mbg.generated Thu May 17 14:04:47 CST 2018
     */
    private Long amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbiz_order_item.courier_company
     *
     * @mbg.generated Thu May 17 14:04:47 CST 2018
     */
    private String courierCompany;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbiz_order_item.courier_number
     *
     * @mbg.generated Thu May 17 14:04:47 CST 2018
     */
    private String courierNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbiz_order_item.send_status
     *
     * @mbg.generated Thu May 17 14:04:47 CST 2018
     */
    private Integer sendStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbiz_order_item.pay_status
     *
     * @mbg.generated Thu May 17 14:04:47 CST 2018
     */
    private Integer payStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbiz_order_item.create_time
     *
     * @mbg.generated Thu May 17 14:04:47 CST 2018
     */
    private OffsetDateTime createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbiz_order_item.update_time
     *
     * @mbg.generated Thu May 17 14:04:47 CST 2018
     */
    private OffsetDateTime updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbiz_order_item.operator
     *
     * @mbg.generated Thu May 17 14:04:47 CST 2018
     */
    private String operator;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbiz_order_item.order_item_id
     *
     * @return the value of tbiz_order_item.order_item_id
     *
     * @mbg.generated Thu May 17 14:04:47 CST 2018
     */
    public Long getOrderItemId() {
        return orderItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbiz_order_item.order_item_id
     *
     * @param orderItemId the value for tbiz_order_item.order_item_id
     *
     * @mbg.generated Thu May 17 14:04:47 CST 2018
     */
    public void setOrderItemId(Long orderItemId) {
        this.orderItemId = orderItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbiz_order_item.order_id
     *
     * @return the value of tbiz_order_item.order_id
     *
     * @mbg.generated Thu May 17 14:04:47 CST 2018
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbiz_order_item.order_id
     *
     * @param orderId the value for tbiz_order_item.order_id
     *
     * @mbg.generated Thu May 17 14:04:47 CST 2018
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbiz_order_item.product_id
     *
     * @return the value of tbiz_order_item.product_id
     *
     * @mbg.generated Thu May 17 14:04:47 CST 2018
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbiz_order_item.product_id
     *
     * @param productId the value for tbiz_order_item.product_id
     *
     * @mbg.generated Thu May 17 14:04:47 CST 2018
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbiz_order_item.business_id
     *
     * @return the value of tbiz_order_item.business_id
     *
     * @mbg.generated Thu May 17 14:04:47 CST 2018
     */
    public Integer getBusinessId() {
        return businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbiz_order_item.business_id
     *
     * @param businessId the value for tbiz_order_item.business_id
     *
     * @mbg.generated Thu May 17 14:04:47 CST 2018
     */
    public void setBusinessId(Integer businessId) {
        this.businessId = businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbiz_order_item.product_count
     *
     * @return the value of tbiz_order_item.product_count
     *
     * @mbg.generated Thu May 17 14:04:47 CST 2018
     */
    public Integer getProductCount() {
        return productCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbiz_order_item.product_count
     *
     * @param productCount the value for tbiz_order_item.product_count
     *
     * @mbg.generated Thu May 17 14:04:47 CST 2018
     */
    public void setProductCount(Integer productCount) {
        this.productCount = productCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbiz_order_item.product_price
     *
     * @return the value of tbiz_order_item.product_price
     *
     * @mbg.generated Thu May 17 14:04:47 CST 2018
     */
    public Integer getProductPrice() {
        return productPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbiz_order_item.product_price
     *
     * @param productPrice the value for tbiz_order_item.product_price
     *
     * @mbg.generated Thu May 17 14:04:47 CST 2018
     */
    public void setProductPrice(Integer productPrice) {
        this.productPrice = productPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbiz_order_item.amount
     *
     * @return the value of tbiz_order_item.amount
     *
     * @mbg.generated Thu May 17 14:04:47 CST 2018
     */
    public Long getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbiz_order_item.amount
     *
     * @param amount the value for tbiz_order_item.amount
     *
     * @mbg.generated Thu May 17 14:04:47 CST 2018
     */
    public void setAmount(Long amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbiz_order_item.courier_company
     *
     * @return the value of tbiz_order_item.courier_company
     *
     * @mbg.generated Thu May 17 14:04:47 CST 2018
     */
    public String getCourierCompany() {
        return courierCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbiz_order_item.courier_company
     *
     * @param courierCompany the value for tbiz_order_item.courier_company
     *
     * @mbg.generated Thu May 17 14:04:47 CST 2018
     */
    public void setCourierCompany(String courierCompany) {
        this.courierCompany = courierCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbiz_order_item.courier_number
     *
     * @return the value of tbiz_order_item.courier_number
     *
     * @mbg.generated Thu May 17 14:04:47 CST 2018
     */
    public String getCourierNumber() {
        return courierNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbiz_order_item.courier_number
     *
     * @param courierNumber the value for tbiz_order_item.courier_number
     *
     * @mbg.generated Thu May 17 14:04:47 CST 2018
     */
    public void setCourierNumber(String courierNumber) {
        this.courierNumber = courierNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbiz_order_item.send_status
     *
     * @return the value of tbiz_order_item.send_status
     *
     * @mbg.generated Thu May 17 14:04:47 CST 2018
     */
    public Integer getSendStatus() {
        return sendStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbiz_order_item.send_status
     *
     * @param sendStatus the value for tbiz_order_item.send_status
     *
     * @mbg.generated Thu May 17 14:04:47 CST 2018
     */
    public void setSendStatus(Integer sendStatus) {
        this.sendStatus = sendStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbiz_order_item.pay_status
     *
     * @return the value of tbiz_order_item.pay_status
     *
     * @mbg.generated Thu May 17 14:04:47 CST 2018
     */
    public Integer getPayStatus() {
        return payStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbiz_order_item.pay_status
     *
     * @param payStatus the value for tbiz_order_item.pay_status
     *
     * @mbg.generated Thu May 17 14:04:47 CST 2018
     */
    public void setPayStatus(Integer payStatus) {
        this.payStatus = payStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbiz_order_item.create_time
     *
     * @return the value of tbiz_order_item.create_time
     *
     * @mbg.generated Thu May 17 14:04:47 CST 2018
     */
    public OffsetDateTime getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbiz_order_item.create_time
     *
     * @param createTime the value for tbiz_order_item.create_time
     *
     * @mbg.generated Thu May 17 14:04:47 CST 2018
     */
    public void setCreateTime(OffsetDateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbiz_order_item.update_time
     *
     * @return the value of tbiz_order_item.update_time
     *
     * @mbg.generated Thu May 17 14:04:47 CST 2018
     */
    public OffsetDateTime getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbiz_order_item.update_time
     *
     * @param updateTime the value for tbiz_order_item.update_time
     *
     * @mbg.generated Thu May 17 14:04:47 CST 2018
     */
    public void setUpdateTime(OffsetDateTime updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbiz_order_item.operator
     *
     * @return the value of tbiz_order_item.operator
     *
     * @mbg.generated Thu May 17 14:04:47 CST 2018
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbiz_order_item.operator
     *
     * @param operator the value for tbiz_order_item.operator
     *
     * @mbg.generated Thu May 17 14:04:47 CST 2018
     */
    public void setOperator(String operator) {
        this.operator = operator;
    }
}