version: "3"

services:
    jce_java:
        build: ./docker-jce-jre
        image: avail/jce-java
        read_only: true
        command: echo "jce java"
        environment:
            - TZ=Asia/Shanghai